### ISSUE TITLE
singlem_appraise error

### ISSUE THREAD

**Issue by microbemarsh** [rhysnewell/aviary#157] opened 2023-10-13 13:09 UTC
Hi Rhys,

I've been running some pretty low coverage nanopore-only runs and have been getting this error on a couple different datasets. I am running on a new server but these did work prior on my cluster system. Any help would be greatly appreciated!

[singlem_error.txt](https://github.com/rhysnewell/aviary/files/12893761/singlem_error.txt)

**Comment by rhysnewell** [comment] 2023-10-13 20:52
Hey @microbemarsh,

Could you please check the singlem log file located here: `data/singlem_out/singlem_log.txt` and post any errors that might be in there

Cheers,
Rhys

**Comment by microbemarsh** [comment] 2023-10-14 15:26
Hi Rhys,

Here is the entirety of the singlem_log.txt:

`usage: singlem [-h]
               {data,pipe,appraise,seqs,makedb,query,summarise,read_fraction,renew,create,get_tree,regenerate,metapackage,chainsaw,condense,trim_package_hmms,supplement}
               ...
singlem: error: unrecognized arguments: --otu_table data/singlem_out/genomes.otu_table.csv`

**Comment by wwood** [comment] 2023-10-14 20:58
Hi @microbemarsh this is likely caused by singlem being updated recently (in conda and pip). Part of the (very large) update was changing from underscores to dashes fully in args i.e. `--otu-table` not `--otu_table`, hence the error you are seeing.

We are tracking some updates to the SingleM integration into Aviary here
https://github.com/rhysnewell/aviary/pull/156

In the meantime, is this causing Aviary to fail, or are you just diligently looking through the logs for errors and kindly letting us know?
Thanks.

**Comment by microbemarsh** [comment] 2023-10-14 21:03
Hi @wwood, 

Unfortunately this has been causing aviary to fail. Do you think if I went though the aviary script and changed the underscore to dashes this may allow the pipeline to continue?

**Comment by wwood** [comment] 2023-10-14 21:19
That probably would work too, but for the moment might be easier to restrict the singlem version in the conda env.

I've done that in https://github.com/rhysnewell/aviary/pull/159 if you would like to use that. Not fully tested since it is the weekend... let us know if that suddenly stops working for you.

**Comment by microbemarsh** [comment] 2023-10-18 19:05
Hi @rhysnewell ,

I'm still running into some single errors but this time with 0.82. The singlem_log.txt file is:
`usage: singlem pipe [-h] [--debug] [--version] [--quiet] [--full_help]
                    --sequences sequence_files) [sequence_file(s) ...]
                    [--reverse sequence_file(s) [sequence_file(s ...]]
                    [--otu_table filename] [--threads num_threads]
                    [--assignment_method {pplacer,diamond,diamond_example}]
                    [--output_extras] [--archive_otu_table filename]
                    [--working_directory directory]
                    [--working_directory_tmpdir] [--force]
                    [--output_jplace filename] [--evalue EVALUE]
                    [--min_orf_length length] [--restrict_read_length length]
                    [--filter_minimum_protein length]
                    [--filter_minimum_nucleotide length] [--include_inserts]
                    [--known_otu_tables KNOWN_OTU_TABLES [KNOWN_OTU_TABLES ...]]
                    [--singlem_packages SINGLEM_PACKAGES [SINGLEM_PACKAGES ...]]
                    [--no_assign_taxonomy] [--known_sequence_taxonomy FILE]
singlem pipe: error: the following arguments are required: --sequences/--forward` 

which caused the entire pipeline to fail with the error code in the text file below. It's not very crucial as the pipeline mostly completed and I was able to get the bins and their statistics but just wanted to follow up.

[singlem_0.82_error.txt](https://github.com/rhysnewell/aviary/files/13032822/singlem_0.82_error.txt)

Thanks again,
Austin

**Comment by wwood** [comment] 2023-10-23 04:44
Hi,

It seems that some changes were merged unintentionally into 0.8.2, causing this - in particular at least this commit
https://github.com/rhysnewell/aviary/pull/156/commits/baadfcb6daf0257c2f133114db19545bd824d0a0

Apologies. I'm on holidays for a bit, but can take a look on return or maybe @AroneyS can finish #156 and be done with this?

**Comment by AroneyS** [comment] 2023-11-20 03:45
Fixed by https://github.com/rhysnewell/aviary/pull/156

**Closed by AroneyS** 2023-11-20 03:45 UTC
