### ISSUE TITLE
SPAdes not running during hybrid assembly mode

### ISSUE THREAD

**Issue by hisatakeishida** [rhysnewell/aviary#163] opened 2023-10-18 06:02 UTC
Hello [@rhysnewell](https://github.com/rhysnewell),

We are trying to run aviary 0.8.1 for hybrid assembly with Illumina and Nanopore dataset.

`aviary assemble` finishes with no errors, however, we noticed that there were no contings generated from Illumina reads in the final assembly output. 
- All the contig ids in `/assembly/final_contigs.fasta` are >contig_XXX_pilon. 
- `/logs/spades_assembly.log` and `/data/spades_assembly/` are empty. 
- `/benchmarks/spades_assembly.benchmark.txt ` says the assembly took less than one second. 
- ` /data/short_reads.filt.fastq.gz` is empty

For our dataset, it is unlikely that all of our Illumina reads are mapping to Flye output.

Please find the aviary subcommand we used below:
```
aviary assemble -1 11049_4_R1.fastq.gz -2 11049_4_R2.fastq.gz --longreads 11049_4_longreads.fastq.gz --longread_type ont_hq --max-threads 80 --n-cores 80 --max_memory 800 --output 11049_hybrid --clean False
```

We used samtools to investigate `/data/sr_vs_long.sort.bam` that was generated during rule filter_illumina_assembly. I believe filter_illumina_assembly tries to recover Illumina reads that do not map to `flye_high_cov.fasta` using following command according to `/logs/filter_illumina_assembly.log`

```
minimap2 -ax sr -t 48 /data/flye_high_cov.fasta /data/short_reads.fastq.gz | samtools view -b -@ 48 | samtools sort -@ 48 -o /data/sr_vs_long.sort.bam 
samtools bam2fq -@ 48 -f 12 data/sr_vs_long.sort.bam | pigz -p 48 > data/short_reads.filt.fastq.gz
```

It seems all the reads in `/data/short_reads.fastq.gz` are unpaired and there are no unmapped entries whose mate is also unmapped (-f 12) in `/data/sr_vs_long.sort.bam`. Thus, samtools bam2fq -f 12 is generating empty ` /data/short_reads.filt.fastq.gz`. 

```
samtools view -c -f 12 data/sr_vs_long.sort.bam
0

samtools view -c -f 4 /data/sr_vs_long.sort.bam
7006387

samtools flagstat -c data/sr_vs_long.sort.bam
7021434 + 0 in total (QC-passed reads + QC-failed reads)
7020080 + 0 primary
0 + 0 secondary
1354 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
15047 + 0 mapped (0.21% : N/A)
13693 + 0 primary mapped (0.20% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

However, when we mapped the original input reads (`-1 11049_4_R1.fastq.gz -2 11049_4_R2.fastq.gz`) against `/data/flye_high_cov.fasta`, instead of `data/short_reads.fastq.gz`, we recovered lots of unmapped entries whose mate is also unmapped (-f 12). 

```
minimap2 -ax sr -t 48 /data/flye_high_cov.fasta 11049_4_R1.fastq.gz 11049_4_R2.fastq.gz | samtools view -b -@ 48 | samtools sort -@ 48 -o /debugging/sr_vs_long_pair.sort.bam

samtools view -c -f 12 /debugging/sr_vs_long_pair.sort.bam
7001964

samtools flagstat /debugging/sr_vs_long_pair.sort.bam
7021417 + 0 in total (QC-passed reads + QC-failed reads)
7020080 + 0 primary
0 + 0 secondary
1337 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
15811 + 0 mapped (0.23% : N/A)
14474 + 0 primary mapped (0.21% : N/A)
7020080 + 0 paired in sequencing
3510040 + 0 read1
3510040 + 0 read2
9982 + 0 properly paired (0.14% : N/A)
10832 + 0 with itself and mate mapped
3642 + 0 singletons (0.05% : N/A)
312 + 0 with mate mapped to a different chr
181 + 0 with mate mapped to a different chr (mapQ>=5)
```

It seems that 0 short reads were recovered during rule filter_illumina_assembly since reads are not paired after the concatenation in rule rule qc_short_reads, and thus, we do not recover any sequences with -f12 flag of samtools?

`aviary assemble` then seems to proceed with empty `short_reads.filt.fastq.gz` for SPAdes. 

We suspect this may be associated with recent script changes in rule qc_short_reads? 

Aviary assemble works perfect when it is running with no Nanopore dataset (i.e. Illumina assembly).

We will appreciate any insight for this.

Best regards,
Hisatake Ishida

[@ StevenJRobbins](https://github.com/StevenJRobbins)

**Comment by rhysnewell** [comment] 2023-10-18 06:43
Hello and thank you for the detailed report. We'll have to dig into this and see why our tests didn't pick this up, it should be an easy enough fix. But just to clarify, is this an issue you've seen across multiple assemblies or have only just noticed with this assembly?

**Comment by hisatakeishida** [comment] 2023-10-18 07:01
Hello, 

Thank you for your quick response!

We have seen this across multiple assemblies, including our >20 samples (ONT+ILL) and a dataset publicly available for a galaxy tutorial (ONT+ILL). 

We are curerntly trying the test data provided in Aviary repository and see if we will get this issue.

**Comment by rhysnewell** [comment] 2023-10-25 22:03
Hi @hisatakeishida,

Apologies for the delay on this. This does not seem to reproducing on our test data, but still investigating. Could you please post the first few full read names present within `short_reads.fastq.gz`. When checking on my end, this file definitely contained paired reads, but `fastp` might be failing due to how the fastq headers are formed in your samples

**Comment by hisatakeishida** [comment] 2023-10-25 23:44
Hello [@rhysnewell](https://github.com/rhysnewell),

Thank you for investigating this. 

Please see below for first few full read names present within` short_reads.fastq.gz` for two test dataset we have tried.

Test data 1 from our samples. 
`@A00632:314:HLTVMDSX5:1:1101:12093:1110 1:N:0:CGATCAGT+NTAGAGAG
@A00632:314:HLTVMDSX5:1:1101:1470:1125 1:N:0:CGATCAGT+NTAGAGAG
@A00632:314:HLTVMDSX5:1:1101:9127:1204 1:N:0:CGATCAGT+NTAGAGAG
@A00632:314:HLTVMDSX5:1:1101:1805:1297 1:N:0:CGATCAGT+ATAGAGAG
@A00632:314:HLTVMDSX5:1:1101:18692:1329 1:N:0:CGATCAGT+ATAGAGAG
@A00632:314:HLTVMDSX5:1:1101:16694:1376 1:N:0:CGATCAGT+ATAGAGAG
@A00632:314:HLTVMDSX5:1:1101:21486:1376 1:N:0:CGATCAGT+ATAGAGAG
@A00632:314:HLTVMDSX5:1:1101:31331:1423 1:N:0:CGATCAGT+ATAGAGAG
@A00632:314:HLTVMDSX5:1:1101:21920:1438 1:N:0:CGATCAGT+ATAGAGAG
@A00632:314:HLTVMDSX5:1:1101:3884:1454 1:N:0:CGATCAGT+ATAGAGAG`

Test data 2 from https://usegalaxy.org.au/published/history?id=53136ff50500dc67 
`@A00401:188:HMKTKDRXX:1:1101:1678:1016 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:8305:1031 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:6036:1047 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:17083:1047 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:6605:1063 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:21540:1063 1:N:0:TAATGTGTAT+CTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:19217:1078 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:13187:1094 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:32461:1094 1:N:0:TAATGTGTCT+GTAAGGCATA
@A00401:188:HMKTKDRXX:1:1101:24840:1110 1:N:0:TAATGTGTCT+GTAAGGCATA`

By any chance, would you be able to share your test data?

Best regards,
Hisatake Ishida

**Comment by rhysnewell** [comment] 2023-10-25 23:48
Interesting, when I run aviary on the data you linked on galaxy the headers I get are:
```
@ERR2935851.1 HWI-C00124:212:C9T75ANXX:4:1101:3159:2229/1
@ERR2935851.1 HWI-C00124:212:C9T75ANXX:4:1101:3159:2229/2
@ERR2935851.3 HWI-C00124:212:C9T75ANXX:4:1101:8742:2219/1
@ERR2935851.3 HWI-C00124:212:C9T75ANXX:4:1101:8742:2219/2
@ERR2935851.5 HWI-C00124:212:C9T75ANXX:4:1101:9927:2233/1
@ERR2935851.5 HWI-C00124:212:C9T75ANXX:4:1101:9927:2233/2
@ERR2935851.6 HWI-C00124:212:C9T75ANXX:4:1101:13470:2234/1
@ERR2935851.6 HWI-C00124:212:C9T75ANXX:4:1101:13470:2234/2
@ERR2935851.7 HWI-C00124:212:C9T75ANXX:4:1101:13673:2216/1
@ERR2935851.7 HWI-C00124:212:C9T75ANXX:4:1101:13673:2216/2
@ERR2935851.10 HWI-C00124:212:C9T75ANXX:4:1101:14967:2248/1
@ERR2935851.10 HWI-C00124:212:C9T75ANXX:4:1101:14967:2248/2
@ERR2935851.11 HWI-C00124:212:C9T75ANXX:4:1101:19554:2236/1
@ERR2935851.11 HWI-C00124:212:C9T75ANXX:4:1101:19554:2236/2
@ERR2935851.15 HWI-C00124:212:C9T75ANXX:4:1101:1062:2456/1
@ERR2935851.15 HWI-C00124:212:C9T75ANXX:4:1101:1062:2456/2
```

Correctly paired, and also the read names are very different. How are you downloading that galaxy data? Even if aviary was unpairing the data it should still have the /1 or /2 in the header to indicate which file it came from. Yours is completely absent.

The test data is under the tests/ folder in the aviary github

Cheers,
Rhys

**Comment by hisatakeishida** [comment] 2023-10-25 23:55
Thank you for your quick response. 

The galaxy test dataset was provided by my colleague. I might try re-dowanloading again. 

Let me investigate this again with the tests/ folder in the aviary github.

**Comment by rhysnewell** [comment] 2023-10-26 00:03
You should also check what the formatting of the read headers are in your original files. If the reads don't contain a pair discriminator then I'm not sure if `fastp` will be able to correctly parse them when running QC

**Comment by StevenJRobbins** [comment] 2023-10-26 03:12
Hi Rhys, 

Thanks for getting back to us. I've looked into other read sets I have, some produced by CMR's sequencing service and others produced by ACE years ago, and none have these /1 and /2 identifiers as supplied by the sequencing centres as separate R1 and R2 files, so these identifiers seem non-standard for R1 and R2 files. Or are you saying that these identifiers should get added when creating the interleaved file? If so, is it not Aviary that's failing to append the /1 and /2 identifiers when it creates the interleaved short_reads.fastq.gz file and therefore causing fastp to fail?

**Comment by rhysnewell** [comment] 2023-10-26 03:31
Hey Steve,

I've looked into this more, and it isn't always `/1` or `/2` as listed here: https://help.basespace.illumina.com/files-used-by-basespace/fastq-files
In your example it is the first number of the second grouping that determines which pair it is, which makes sense. 

Just to explain how the read qc works:
Aviary is just making a call to `fastp` using the reads provided using a command similar to this:
```
fastp --stdout -w 8 -q 15 -u 40 -l 15 --length_limit 0 -i data/short_reads.pre_qc.1.fastq.gz -I data/short_reads.pre_qc.2.fastq.gz
```
(You can find the actual command being made to `fastp` in the `logs/qc_short_reads.log`) file. For non-coassembled runs, these `pre_qc` fastq files are just symlinks to the reads provided by the user. We do this to make runs consistent between coassembly and non-coassembly. 

What you can do to test this is provide your reads to `fastp` directly, you'll note that it will probably give the same result. Both aviary and fastp are expecting the read headers of paired end reads to match up, as would many other tools like spades and minimap. Some of these tools might do this by just looking for direct matches between fastq headers (direct string matching)

If you could run `fastp` on your reads and then see if the output contains correclty interleaved reads then that would be very helpful as I don't have access to reads with headers in that format. The glaxy data I download has the other format.

**Comment by hisatakeishida** [comment] 2023-10-26 04:36
Hello [@rhysnewell](https://github.com/rhysnewell), 

I re-downladed the galaxy tutorial files from https://usegalaxy.org.au/published/history?id=53136ff50500dc67. 

I confirmed these files have /1 and /2 identifiers as follow
```
zcat /scratch/project/ncmas_d85/ishida/galaxy_test_data/Galaxy_test_illumina_R1.fastq.gz | grep "@" | head -n 5
@ERR2935851.1 HWI-C00124:212:C9T75ANXX:4:1101:3159:2229/1
@ERR2935851.2 HWI-C00124:212:C9T75ANXX:4:1101:5667:2208/1
@ERR2935851.3 HWI-C00124:212:C9T75ANXX:4:1101:8742:2219/1
@ERR2935851.4 HWI-C00124:212:C9T75ANXX:4:1101:9630:2190/1
@ERR2935851.5 HWI-C00124:212:C9T75ANXX:4:1101:9927:2233/1

zcat /scratch/project/ncmas_d85/ishida/galaxy_test_data/Galaxy_test_illumina_R2.fastq.gz  | grep "@" | head -n 5
@ERR2935851.1 HWI-C00124:212:C9T75ANXX:4:1101:3159:2229/2
@ERR2935851.2 HWI-C00124:212:C9T75ANXX:4:1101:5667:2208/2
@ERR2935851.3 HWI-C00124:212:C9T75ANXX:4:1101:8742:2219/2
@ERR2935851.4 HWI-C00124:212:C9T75ANXX:4:1101:9630:2190/2
@ERR2935851.5 HWI-C00124:212:C9T75ANXX:4:1101:9927:2233/2
```

Then, I ran Aviary assemble as follows 
```
aviary assemble -1 /scratch/project_mnt/S0026/ishida/galaxy_test_data/Galaxy_test_illumina_R1.fastq.gz -2 /scratch/project_mnt/S0026/ishida/galaxy_test_data/Galaxy_test_illumina_R2.fastq.gz --longreads /scratch/project_mnt/S0026/ishida/galaxy_test_data/Galaxy_test_nanopore.fastq.gz --longread_type ont --min-read-size 10 --max-threads 48 --n-cores 48 --max_memory 800 --output /scratch/project_mnt/S0026/ishida/galaxy_test_data/assembly --clean False
```

Aviary says it finished with no error, but short_reads.filt.fastq.gz seems empty and took one second for short assembly part. 

Checking contig ids in assembly output. 
```
grep ">" /scratch/project/ncmas_d85/ishida/galaxy_test_data/assembly/assembly/final_contigs.fasta 
>contig_23_pilon LN:i:17662 RC:i:7434 XC:f:1.000000
>contig_12_pilon LN:i:14438 RC:i:5455 XC:f:1.000000
>contig_9_pilon LN:i:155343 RC:i:64453 XC:f:0.996785
>contig_10_pilon LN:i:179331 RC:i:59999 XC:f:1.000000
>contig_13_pilon LN:i:167055 RC:i:67304 XC:f:1.000000
>contig_21_pilon LN:i:234564 RC:i:69054 XC:f:1.000000
>contig_19_pilon LN:i:351967 RC:i:120713 XC:f:1.000000
>contig_4_pilon LN:i:269136 RC:i:99500 XC:f:1.000000
>contig_3_pilon LN:i:15095 RC:i:6922 XC:f:1.000000
>contig_14_pilon LN:i:463482 RC:i:159905 XC:f:1.000000
>contig_7_pilon LN:i:174866 RC:i:71645 XC:f:1.000000
>contig_22_pilon LN:i:215928 RC:i:67715 XC:f:0.995370
>contig_15_pilon LN:i:96964 RC:i:34175 XC:f:1.000000
>contig_8_pilon LN:i:171241 RC:i:62102 XC:f:1.000000
>contig_1_pilon LN:i:55394 RC:i:26041 XC:f:1.000000
>contig_18_pilon LN:i:149806 RC:i:58909 XC:f:1.000000
>contig_11_pilon LN:i:30786 RC:i:14869 XC:f:1.000000
>contig_17_pilon LN:i:204126 RC:i:76770 XC:f:1.000000
>contig_6_pilon LN:i:166907 RC:i:54995 XC:f:1.000000
>contig_20_pilon LN:i:689544 RC:i:260404 XC:f:1.000000
>contig_2_pilon LN:i:139352 RC:i:54011 XC:f:1.000000
>contig_5_pilon LN:i:27706 RC:i:13161 XC:f:1.000000 
```

Checking final_contigs.fasta and flye_high_cov.fasta with seqkit stats. They seem identical, suggesting no output from short reads?
```
seqkit stats /scratch/project/ncmas_d85/ishida/galaxy_test_data/assembly/assembly/final_contigs.fasta -T --all -j 32
file    format  type    num_seqs        sum_len min_len avg_len max_len Q1      Q2      Q3      sum_gap N50     Q20(%)  Q30(%)  GC(%)
/scratch/project/ncmas_d85/ishida/galaxy_test_data/assembly/assembly/final_contigs.fasta        FASTA   DNA     22      3990693 14438   181395.1        689544  55394.0 166981.0        215928.0        0       234564  0.00    0.00    43.78

seqkit stats /scratch/project/ncmas_d85/ishida/galaxy_test_data/assembly/data/flye_high_cov.fasta -T --all -j 32
file    format  type    num_seqs        sum_len min_len avg_len max_len Q1      Q2      Q3      sum_gap N50     Q20(%)  Q30(%)  GC(%)
/scratch/project/ncmas_d85/ishida/galaxy_test_data/assembly/data/flye_high_cov.fasta    FASTA   DNA     22      3990693 14438   181395.1        689544  55394.0 166981.0        215928.0        0       234564  0.00    0.00    43.78
```

Do you similar output in your trial run for the galaxy test data?

I also tried test data under the tests/ folder in the aviary github. 

```
aviary assemble -1 /scratch/project_mnt/S0026/ishida/aviary_repo_test/wgsim.1.fq.gz -2 /scratch/project_mnt/S0026/ishida/aviary_repo_test/wgsim.2.fq.gz --longreads /scratch/project_mnt/S0026/ishida/aviary_repo_test/pbsim.fq.gz --longread_type ont --min-read-size 10 --max-threads 48 --n-cores 48 --max_memory 800 --output /scratch/project_mnt/S0026/ishida/aviary_repo_test/assembly_test --clean False
```

According to logs/flye_assembly.log, it aborted as follows 
```
[2023-10-26 14:16:36] ERROR: No reads above minimum length threshold (1000)
[2023-10-26 14:16:36] ERROR: Pipeline aborted 
```

Did your test run finish with no error using the test data in tests/ folder in Aviary github?

Best regards,
Hisatake Ishida

**Comment by rhysnewell** [comment] 2023-10-26 05:01
```
minimap2 -ax sr -t 48 /scratch/project/ncmas_d85/ishida/galaxy_test_data/assembly/data/flye_high_cov.fasta /scratch/project/ncmas_d85/ishida/galaxy_test_data/Galaxy_test_illumina_R1.fastq.gz /scratch/project/ncmas_d85/ishida/galaxy_test_data/Galaxy_test_illumina_R2.fastq.gz | samtools view -b -@ 48 | samtools sort -@ 48 -o Test_sr_vs_long.sort.bam 

samtools view -c -f 12 Test_sr_vs_long.sort.bam
42120
```

Here you should be mapping the `data/short_reads.fastq.gz` reads and not the original reads. QC might be removing a lot of the reads that aren't mapping

**Comment by rhysnewell** [comment] 2023-10-26 05:07
N.B. short_reads.fastq.gz gets deleted by aviary regardless of `--clean`, so just run aviary as normal but add `-w qc_short_reads` and you will see them appear

**Comment by rhysnewell** [comment] 2023-10-26 05:10
Another note, when I run this same sample through my `short_reads.filt.fastq.gz` contains 24608 reads:
```
zcat short_reads.filt.fastq.gz | bat -S | rg "@" | wc -l
24608
```

and I have spades assembly with 66 contigs:
```
rg ">" spades_assembly.fasta | wc -l
66
```

Same sample, and same command. I think you might need to update aviary or something wrong has happened with your installation

**Comment by rhysnewell** [comment] 2023-10-26 22:02
I just noticed you are using aviary 0.8.1, and I'm using the latest version 0.8.2. You probably just need to update your installation

**Comment by hisatakeishida** [comment] 2023-10-30 07:47
Yes I have been using aviary 0.8.1. I will try 0.8.2. Thanks for your help!

**Comment by rhysnewell** [comment] 2023-11-05 22:24
Hi @hisatakeishida,

Was this issue resolved by upgrading to a newer version?

Cheers,
Rhys

**Comment by hisatakeishida** [comment] 2023-11-08 23:43
Hello Rhys, 

I have not been able to test this yet, I will let you know when I try with the newer version 

Best regards,
Hisatake Ishida

**Closed** 2023-11-20 03:53 UTC

**Comment by hisatakeishida** [comment] 2024-01-11 02:46
Hello [@rhysnewell](https://github.com/rhysnewell),

Sorry for the late update, but Aviary 0.8.3 runs Hybrid mode smoothly!
It seems the issue was specific to 0.8.1.

Thanks,
Hisatake
