### ISSUE TITLE
aviary recover with short reads 

### ISSUE THREAD

**Issue by cifuj** [rhysnewell/aviary#36] opened 2022-03-14 13:49 UTC
Hi! 
I wanted to use aviary to recover bins using the combined binnig strategies, specially Rosella and vamb. 
For the moment I only have short read libraries. When I try to run `aviary recover` without specifying `--longreads ` I get the following error: 
```
MissingInputException in line 10 of /tools/aviary/aviary/modules/quality_control/qc.smk:
Missing input files for rule link_reads:
    output: data/long_reads.fastq.gz
    affected files:
        none
```
Is it possible to run aviary on a "short-read" mode only? 

Best,
Jeronimo

**Comment by rhysnewell** [comment] 2022-03-14 21:53
Hi Jeronimo,

It should definitely be possible to run aviary in short read only mode, this is a bit of an odd error. Could you send me through the full command that you ran, and I'll try and replicate it?

Cheers,
Rhys

**Comment by cifuj** [comment] 2022-03-15 08:33
Hi Rhys,

I tried using the assembly of that library and without assembly.  
```
aviary recover -1 reads/5289_D_R1.fq.gz -2 reads/5289_D_R2.fq.gz  --output aviary_5289_D/ --max_threads 12 --n_cores 24 
aviary recover --assembly contigs_5289_D.fa -1 reads/5289_D_R1.fq.gz -2 reads/5289_D_R2.fq.gz  --output aviary_5289_D/ --max_threads 12 --n_cores 24
```

Best,
Jeronimo

**Comment by rhysnewell** [comment] 2022-03-15 08:34
Thanks Jeronimo,

And which version/commit of aviary are you using?

**Comment by cifuj** [comment] 2022-03-15 08:37
aviary 0.3.2

**Comment by rhysnewell** [comment] 2022-03-15 08:43
Okay, not exactly sure what would be causing this and I can't seem to replicate it based on your command. Could you just check that the relative paths to the reads and assembly are correct? If they are maybe try using absolute paths?

I'd also recommend updating to aviary 0.3.3 which came out today, the latest commit on the main branch

**Comment by rhysnewell** [comment] 2022-03-15 10:14
Keep me posted on any updates you have on this, keen to get it working for you!

**Comment by cifuj** [comment] 2022-03-15 11:11
Thank you Rhys! I updated aviary and tried again. This time it worked, so it must have been a problem on my side. 
I was able to run rosella, maxbin, metabat and concoct. However, I could not run the complete pipeline because problems with vamb. [same as here](https://github.com/RasmussenLab/vamb/issues/65). 
```
Traceback (most recent call last):
  File "/home/jcifuentes/.conda/c909a5fef9d5b15192720b7a91e947de/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/home/jcifuentes/.conda/c909a5fef9d5b15192720b7a91e947de/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/home/jcifuentes/.conda/c909a5fef9d5b15192720b7a91e947de/lib/python3.7/site-packages/vamb/__main__.py", line 247, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/home/jcifuentes/.conda/c909a5fef9d5b15192720b7a91e947de/lib/python3.7/site-packages/vamb/__main__.py", line 121, in calc_rpkm
    raise ValueError("Length of TNFs and length of RPKM does not match. Verify the inputs")
ValueError: Length of TNFs and length of RPKM does not match. Verify the inputs
[Tue Mar 15 11:21:35 2022]
```
I also had problems with the version of GTDB-Tk. aviary uses GTDB-Tk v1.5.0 and I used r95, so I have to download and provide r202.

**Comment by rhysnewell** [comment] 2022-03-15 11:23
Aviary should continue if any of the binners throw an error like that, did you keyboard interrupt it once it threw that error or did it stop itself?

Vamb is certainly a tricky binner to get to run consistently, I'm not sure what would make it throw out this error all of a sudden. I'll look into it and see if I can reproduce it. In the mean time, could you please attach the full error log produce by snakemake if you have it available?

**Comment by cifuj** [comment] 2022-03-15 11:31
aviary continued and it finished the binning and refinement of the bins obtained with rosella, maxbin, metabat and concoct.
I don't have the snakemake.log file but I have attached what was printed to the screen
[aviary_log_20220315.txt](https://github.com/rhysnewell/aviary/files/8252768/aviary_log_20220315.txt).

**Comment by rhysnewell** [comment] 2022-03-15 22:40
Hmm, If I had to guess I'd say vamb failing for you might once again be a special case. Your assembly and metagenome seem rather low complexity, I wonder if vamb has difficulty dealing with such a small dataset. Nonetheless, aviary seems to be handling things as expected so I might go ahead and close this issue. If you have any other problems, please feel free to open up a new issue

Cheers,
Rhys

**Closed by rhysnewell** 2022-03-15 22:40 UTC
