### ISSUE TITLE
singleM output. Filesystem latency?

### ISSUE THREAD

**Issue by sternp** [rhysnewell/aviary#15] opened 2021-02-04 02:51 UTC
```
Building DAG of jobs...

Using shell: /bin/bash
Provided cores: 100
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	recover_mags
	1
busco_folder does not point to a folder

[Thu Feb  4 12:43:12 2021]
rule recover_mags:
    input: data/das_tool_bins/done, data/gtdbtk/done, data/checkm.out, data/coverm_abundances.tsv
    output: data/singlem_out/singlem_appraise.svg, data/done
    jobid: 0
    threads: 100

Activating conda environment: /home/sternesp/.conda/envs/d7c39ec7
[2021-02-04T02:43:14Z INFO  bird_tool_utils::clap_utils] coverm version 0.3.0
[2021-02-04T02:43:14Z INFO  bird_tool_utils::external_command_checker] Found fastANI version 1.32 
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Reading CheckM tab table ..
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Calculating num_contigs etc. for genome quality assessment ..
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Read in genome qualities for 52 genomes. 52 passed quality thresholds
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Creating output-representative-fasta-directory ..
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Clustering 52 genomes ..
[2021-02-04T02:43:14Z INFO  galah::finch] Sketching MinHash representations of each genome with finch ..
[2021-02-04T02:43:14Z INFO  galah::finch] Finished sketching genomes
[2021-02-04T02:43:14Z INFO  galah::clusterer] Preclustering ..
[2021-02-04T02:43:14Z INFO  galah::clusterer] Found 52 preclusters. The largest contained 1 genomes
[2021-02-04T02:43:14Z INFO  galah::clusterer] Finding representative genomes and assigning all genomes to these ..
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Found 52 genome clusters
[2021-02-04T02:43:14Z INFO  galah::cluster_argument_parsing] Finished printing genome clusters
Waiting at most 5 seconds for missing files.
MissingOutputException in line 460 of /home/sternesp/git/aviary/aviary/Snakefile:
Missing files after 5 seconds:
data/singlem_out/singlem_appraise.svg
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Removing output files of failed job recover_mags since they might be corrupted:
data/done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
Complete log: /lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/log/2021-02-04T124312.637218.snakemake.log
02/04/2021 12:43:19 PM CRITICAL: Command 'snakemake --snakefile /home/sternesp/git/aviary/aviary/Snakefile --directory aviary_output/M360w28 --jobs 100 --rerun-incomplete --configfile 'aviary_output/M360w28/template_config.yaml' --nolock   --use-conda --conda-prefix ~/.conda/envs/   recover_mags   ' returned non-zero exit status 1
```

It recommends trying with `--latency-wait` when trying to output data/singlem_out/singlem_appraise.svg. However I can't figure out which command accepts `--latency-wait` as as parameter.

Also, the busco_folder as specified in the config doesn't exist. Is busco required for this pipeline?

Thanks!

**Comment by rhysnewell** [comment] 2021-02-04 03:32
`--latency-wait` would have to supplied directly the snakemake command which should be found in the `aviary.py` file. Unfortunately, there is no way to parse it from the current aviary wrapper. 

I'm not exactly sure that this is the cause of this error though. I think the singlem stages failed to run or didn't get put into the DAG. Let me just double check this

**Comment by sternp** [comment] 2021-02-04 03:34
Hmm, the singlem_out directory is infact empty

**Comment by rhysnewell** [comment] 2021-02-04 03:35
Yep, the singlem command was set to be the output of a rule when it was meant to be the input so it was never being created. Latest commit on dev fixes that.

Also, busco is being removed so don't worry about that message

**Comment by sternp** [comment] 2021-02-04 03:37
Thanks Rhys.

**Comment by sternp** [comment] 2021-02-04 05:47
It's kicking up a new error now

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 48
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	recover_mags
	1	singlem_appraise
	1	singlem_pipe_reads
	3
busco_folder does not point to a folder
Select jobs to execute...

[Thu Feb  4 15:41:00 2021]
rule singlem_pipe_reads:
    output: data/singlem_out/metagenome.combined_otu_table.csv
    jobid: 15

Activating conda environment: /home/sternesp/.conda/envs/d4d06605
Activating conda environment: /home/sternesp/.conda/envs/d4d06605
Using prexisting directory: data/singlem_out/
Traceback (most recent call last):
  File "/lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/scripts/tmplctlr6ro.singlem_reads.py", line 19, in <module>
    if snakemake.config["interleaved"] != "none":
KeyError: 'interleaved'
[Thu Feb  4 15:41:02 2021]
Error in rule singlem_pipe_reads:
    jobid: 15
    output: data/singlem_out/metagenome.combined_otu_table.csv
    conda-env: /home/sternesp/.conda/envs/d4d06605

RuleException:
CalledProcessError in line 439 of /home/sternesp/git/aviary/aviary/Snakefile:
Command 'source /home/sternesp/anaconda3/bin/activate '/home/sternesp/.conda/envs/d4d06605'; set -euo pipefail;  python /lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/scripts/tmplctlr6ro.singlem_reads.py' returned non-zero exit status 1.
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/home/sternesp/git/aviary/aviary/Snakefile", line 439, in __rule_singlem_pipe_reads
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
Complete log: /lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/log/2021-02-04T154100.063837.snakemake.log
02/04/2021 03:41:02 PM CRITICAL: Command 'snakemake --snakefile /home/sternesp/git/aviary/aviary/Snakefile --directory aviary_output/M360w28 --jobs 48 --rerun-incomplete --configfile 'aviary_output/M360w28/template_config.yaml' --nolock   --use-conda --conda-prefix ~/.conda/envs/   recover_mags   ' returned non-zero exit status 1.
```

**Comment by rhysnewell** [comment] 2021-02-04 05:52
Ah yes, there is indeed no interleaved key. Silly mistake, should be fixed now

**Comment by sternp** [comment] 2021-02-04 06:02
Thanks.

**Comment by sternp** [comment] 2021-02-04 06:16
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 48
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	recover_mags
	1	singlem_appraise
	1	singlem_pipe_reads
	3
busco_folder does not point to a folder
Select jobs to execute...

[Thu Feb  4 16:09:50 2021]
rule singlem_pipe_reads:
    output: data/singlem_out/metagenome.combined_otu_table.csv
    jobid: 15

Activating conda environment: /home/sternesp/.conda/envs/d4d06605
Activating conda environment: /home/sternesp/.conda/envs/d4d06605
Using prexisting directory: data/singlem_out/
Traceback (most recent call last):
  File "/lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/scripts/tmp02eish5d.singlem_reads.py", line 23, in <module>
    (snakemake.pplacer_threads,
AttributeError: 'Snakemake' object has no attribute 'pplacer_threads'
[Thu Feb  4 16:09:53 2021]
Error in rule singlem_pipe_reads:
    jobid: 15
    output: data/singlem_out/metagenome.combined_otu_table.csv
    conda-env: /home/sternesp/.conda/envs/d4d06605

RuleException:
CalledProcessError in line 439 of /home/sternesp/git/aviary/aviary/Snakefile:
Command 'source /home/sternesp/anaconda3/bin/activate '/home/sternesp/.conda/envs/d4d06605'; set -euo pipefail;  python /lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/scripts/tmp02eish5d.singlem_reads.py' returned non-zero exit status 1.
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/home/sternesp/git/aviary/aviary/Snakefile", line 439, in __rule_singlem_pipe_reads
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/sternesp/anaconda3/envs/aviary/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
Complete log: /lustre/scratch/microbiome/sternesp/preeclampsia/aviary_output/M360w28/.snakemake/log/2021-02-04T160950.268934.snakemake.log
```

**Closed** 2021-02-08 02:36 UTC
